kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# comment out what you don't want
# but watch for dependencies.. noted in the `patches`
resources:
- pingaccess
- pingfederate
- ../01-standalone/pingdataconsole
- pingdirectory
- pingdatagovernance
- pingdatagovernancepap
- pingintelligence

# The only difference in standalone deployments vs "fullstack" (integrated) is the product configurations. 
# here we replace standalone server-profiles ("getting-started") with "baseline" for each product
patches:
- path: wait-for-directory.yaml
  target:
    name: pingfederate
    kind: Deployment

- path: wait-for-directory.yaml
  target:
    name: pingdatagovernance
    kind: Deployment

- path: wait-for-federate.yaml
  target:
    name: pingaccess
    kind: Deployment

- path: wait-for-federate.yaml
  target:
    name: pingintelligence
    kind: Deployment