version: "3.1"
#
# This compose file offers mirrors the configuration provided in
# 10-docker-standalone/01-pingdirectory "Simplest way"
# 
#        

networks:
    pingnet:

services:
  pingdirectory:
    image: pingidentity/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingdirectory
      # Variables are added to ~/.pingidentity/devops and sourced by .bash_profile when setup.sh
      # (Getting-started project root directory) is first run to configure your environment.
      # Used to generate just-in-time evaluation licenses
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
    deploy:
      replicas: 1
    ports:
      - 4636:636
      - 4443:443
    networks:
      - pingnet
    volumes:
      - /tmp/Swarm/basic1/pingdirectory:/opt/out
