version: "3.1"

services:
  pingaccess:
    image: pingidentity/pingaccess:${PING_IDENTITY_DEVOPS_TAG}
    command: ["sh", "-c", "wait-for pingfederate:9031 -t 700 -- entrypoint.sh start-server"]
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingaccess
      # Variables are added to ~/.pingidentity/devops and sourced by .bash_profile when setup.sh
      # (Getting-started project root directory) is first run to configure your environment.
      # Used to generate just-in-time evaluation licenses
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
    deploy:
      replicas: 1
    ports:
      - 443:443
      - 9000:9000
    networks:
      - pingnet
  #  volumes:
  #    - /tmp/Swarm/fullstack/pingaccess:/opt/out

  pingfederate-admin:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: ["sh", "-c", "wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server"]
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingfederate
      - DISCOVERY_INITIAL_HOST=pingfederate-admin[7600]
      - OPERATIONAL_MODE=CLUSTERED_CONSOLE
      - CLUSTER_BIND_ADDRESS=match-address:10.10.10.\*
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
    deploy:
      replicas: 1
    ports:
      - 9999:9999
    networks:
      - pingnet

  pingfederate:
    image: pingidentity/pingfederate:${PING_IDENTITY_DEVOPS_TAG}
    command: ["sh", "-c", "wait-for pingfederate-admin:9999 -t 600 -- entrypoint.sh start-server"]
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingfederate
      - DISCOVERY_INITIAL_HOST=pingfederate-admin[7600]
      - OPERATIONAL_MODE=CLUSTERED_ENGINE
      - CLUSTER_BIND_ADDRESS=match-address:10.10.10.\*
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
    deploy:
      replicas: 1
    ports:
      - 9031:9031
    networks:
      - pingnet
    # volumes:
    #  - /tmp/Swarm/fullstack/pingfederate:/opt/out

  pingdirectory:
    image: pingidentity/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
    deploy:
      replicas: 1
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
  #  volumes:
  #    - /tmp/Swarm/fullstack/pingdirectory:/opt/out

  pingdataconsole:
    image: pingidentity/pingdataconsole:${PING_IDENTITY_DEVOPS_TAG}
    deploy:
      replicas: 1
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - pingnet

networks:
  pingnet:
    ipam:
      config:
        - subnet: 10.10.10.0/24