version: "3.1"

services:
  pingdatasync:
    image: pingidentity/pingdatasync:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdatasync
    deploy:
      replicas: 1
    networks:
      - pingnet
    # volumes:
    #   - /tmp/Swarm/simple-sync/pingdatasync:/opt/out

  pingdirectory:
    image: pingidentity/pingdirectory:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=simple-sync/pingdirectory
    deploy:
      replicas: 1
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
    # volumes:
    #   - /tmp/Swarm/simple-sync/pingdirectory:/opt/out

  pingdataconsole:
    image: pingidentity/pingdataconsole:${PING_IDENTITY_DEVOPS_TAG}
    deploy:
      replicas: 1
    ports:
      - 8080:8080
    networks:
      - pingnet
        
networks:
    pingnet:
