version: "3.1"

services:
  pingdatasync:
    image: pingidentity/pingdatasync
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-simple-sync.git
      - SERVER_PROFILE_PATH=pingdatasync
    deploy:
      replicas: 1
    networks:
      - pingnet
    volumes:
      - /tmp/Swarm/simple-sync/pingdatasync:/opt/out

  pingdirectory:
    image: pingidentity/pingdirectory
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-pingidentity-simple-sync.git
      - SERVER_PROFILE_PATH=pingdirectory
    deploy:
      replicas: 1
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
    volumes:
      - /tmp/Swarm/simple-sync/pingdirectory:/opt/out

  pingdataconsole:
    image: pingidentity/pingdataconsole
    deploy:
      replicas: 1
    ports:
      - 8080:8080
    networks:
      - pingnet
        
networks:
    pingnet:
