#!/bin/bash
cd "$( dirname "${0}" )"
THIS="$( basename "${0}" )"
THIS_DIR=`pwd`


numTools=0
numOk=0
numMissing=0

# function to check for the existence of a tool command
check_tool()
{
    toolName="${1}" && shift
    toolCmd="${1}" && shift
    toolMsg="${1}" && shift
    
    numTools=$((numTools + 1))
    ${toolCmd} 2>/dev/null >/dev/null
    RESULT=$?

    pad=$(printf '%0.1s' "."{1..80})
    printf "%s" "${toolName}"
    printf "%*.*s" 0 $((72-${#toolName}-3)) "${pad}"

    if [ "${RESULT}" == "127" ]; then
        echo -e "[ ${RED}MISSING${NC} ]"
        echo "INFO: ${toolMsg}" | sed 's/^/      /'
        echo ""
        numMissing=$((numMissing + 1))
    else
        echo -e "[   ${GREEN}OK${NC}    ]"
        numOk=$((numOk + 1))
    fi
}


RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

echo_red()
{
    echo -e "${RED}$*${NC}"
}

echo_green()
{
    echo -e "${GREEN}$*${NC}"
}

echo "

################################################################################

                     Welcome to Ping Identity DevOps!

  We will run through a few setup items to make your experiance as easy as 
  possible.  If we have recommendations along the way, we'll provide that
  also.
"

echo "
####################### bash_profile_devops ####################################"

grep "bash_profile_devops" ~/.bash_profile > /dev/null

if test "${?}" == "1"; then
  echo "  First, let's add a bunch of DevOps helper alias' and functions to your
  shell.  We are assuming you use bash and will add these to your .bash_profile
"


  echo -n "  OK if we add a 'source bash_profile_devops' commands to your .bash_profile (y/n) [y] ? "
  read answer

  if [ "${answer}" == "" ] || [ "${answer}" == "Y" ] || [ "${answer}" == "y" ]; then
    echo "
# Ping Identity DevOps Aliases - Added with setup on `date`
source ${THIS_DIR}/bash_profile_devops" >> ~/.bash_profile


    echo_green "  OK, we got you setup.  You can get help with 'dhelp' command"
  fi
else
  echo_green "  Great! You already have bash_profile_devops in your .bash_profile"
fi

echo "
####################### Checking Tools #########################################"

#echo "####################### Utilities ##############################################"

check_tool "jq"       "jq -V"           "https://stedolan.github.io/jq/download"
check_tool "pyjwt"    "pyjwt -V"        "https://pyjwt.readthedocs.io/"

#echo "####################### Docker #################################################"
check_tool "docker"   "docker -v"       "https://hub.docker.com/editions/community/docker-ce-desktop-mac"

#echo "####################### Amazon #################################################"

check_tool "aws"      "aws --version"   "https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html"
check_tool "eksctl"   "eksctl version"  "https://eksctl.io/"

#echo "####################### Google #################################################"

check_tool "gcloud"    "gcloud -v"      "https://cloud.google.com/sdk/gcloud/"

#echo "####################### Microsoft ##############################################"

check_tool "az"       "az -V"           "https://docs.microsoft.com/cli/azure/install-azure-cli"

echo ""

echo -e "
####################### RESULTS ################################################

 ${GREEN}     OK: $numOk${NC}
 ${RED}MISSING: $numMissing${NC}

  If there were items to resolve, please complete those now.  Simply 
  rerun '${THIS}' again to validate all steps are complete.

  ${PURPLE}NOTE: In order to get the new aliases, you should restart your shell
  or simply source the bash_profile_devops file.  Just cut/paste the following
  command:

    source ${THIS_DIR}/bash_profile_devops${NC}

################################################################################

  Some great commands to see sample docker or PingOne For Customer commands
  can be found with:

    dhelp     # DevOps Help
    p1help    # PineOne Help
    piconfig  # Ping Identity Configuration Setup

  Drop us a line, let us know how it's going:

    devops_program@pingidentity.com
"
