apiVersion: v1
kind: Service
metadata:
  name: ds-load-balancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "20"
  labels:
    app: pd-label
spec:
  type: LoadBalancer
  ports:
  - name: ldap
    port: 389
  - name: ldaps
    port: 636
  - name: https
    port: 443
  selector:
    app: pd-label
---
apiVersion: v1
kind: Service
metadata:
  name: pd-service-name
spec:
  ports:
    - port: 636
      name: ldaps
    - port: 443
      name: ssl
    - port: 389
      name: ldap
  clusterIP: None
  selector:
    app: pd-label
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: io1
  labels:
    app: pd-label
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  fsType: ext4
  iopsPerGB: "50"
mountOptions:
  - discard
---
apiVersion: v1
kind: Secret
metadata:
  name: passwords
  labels:
    app: pingdirectory
type: Opaque
data:
  # Base64 encoded - 2FederateM0re
  root-user-password: MkZlZGVyYXRlTTByZQ==
  admin-user-password: MkZlZGVyYXRlTTByZQ==
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
  labels:
      app: pd-label
spec:
  serviceName: pd-service-name
  replicas: 1
  selector:
    matchLabels:
      app: pd-label
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: pd-label
    spec:
      volumes:
      # - name: server-profile-ds
      #   configMap:
      #     name: server-profile-ds
      # - name: passwords
      #   secret:
      #     secretName: passwords
      #     defaultMode: 256
      - name: out-dir 
        persistentVolumeClaim:
          claimName: out-dir
      terminationGracePeriodSeconds: 300
      containers:
      - name: ds
        image: pingidentity/pingdirectory:edge
        # command: ["/opt/entrypoint.sh"]
        # args: ["start-server", "tail", "-f", "/dev/null"]
        imagePullPolicy: Always
        ports:
        - containerPort: 636
        - containerPort: 443
        - containerPort: 389
        resources:
          requests:
            memory: "4Gi"
            cpu: "0"
          limits:
            memory: "4Gi"
            cpu: "0"
        env:
        - name: SERVER_PROFILE_URL
          value: "https://www.github.com/pingidentity/pingidentity-server-profiles.git"
        - name: SERVER_PROFILE_PATH
          value: "getting-started/pingdirectory"
        - name: PING_IDENTITY_DEVOPS_USER
          value: ${PING_IDENTITY_DEVOPS_USER}
        - name: PING_IDENTITY_DEVOPS_KEY
          value: ${PING_IDENTITY_DEVOPS_KEY}
        - name: ORCHESTRATION_TYPE
          value: kubernetes
        - name: K8S_STATEFUL_SET_NAME
          value: "ds"
        - name: K8S_STATEFUL_SET_SERVICE_NAME
          value: "pd-service-name"
        - name: TAIL_LOG_FILES
          value: ""
        - name: MAKELDIF_USERS
          value: "1000"
        - name: ENCRYPTION_PASSWORD_FILE
          value: "/opt/staging/pwd"
        volumeMounts:
        - name: out-dir
          mountPath: /opt/out
        readinessProbe:
          exec:
            command: 
              - /bin/sh
              - -c
              - /opt/liveness.sh
          # initialDelaySeconds: 60
          # periodSeconds: 30
        # livenessProbe:
        #   exec:
        #     command:
        #       - /bin/sh
        #       - -c
        #       - /opt/liveness.sh
        # lifecycle:
        #   preStop:
        #     exec:
        #       command: 
        #       - /bin/sh
        #       - -c
        #       - /preStop.sh
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: io1
      resources:
        requests:
          storage: 8Gi

