apiVersion: v1
kind: Service
metadata:
  name: pingdataconsole-service
spec:
  ports:
    - port: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdataconsole-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: pingdataconsole
    spec:
      containers:
      - name: pingdataconsole
        image: pingidentity/pingdataconsole:edge
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1"
          limits:
            memory: "1.5Gi"
            cpu: "1"
