kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- pingaccess-engine.yaml
- pingaccess-admin.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingaccess-engine-environment-variables
  envs:
    - env_vars.pingaccess-engine
- name: pingaccess-admin-environment-variables
  envs:
    - env_vars.pingaccess-admin
