apiVersion: apps/v1
kind: not-important
metadata:
  name: not-important
spec:
  template:
    spec:
      initContainers:
        - name: init
          image: curlimages/curl:latest
          command: ['sh', '-c', 'until curl --connect-timeout 1 --silent -k https://pingdirectory:443/directory/v1 ; do echo waiting for admin ; sleep 2 ; done']
