apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ping
  name: config-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]