{
 "title": "Ping Identity Performance Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "range_interval", "label": "range_interval", "query": "1m" },
   { "name": "data_source", "query": "influxdb" },
   { "name": "jm_database", "query": "SHOW DATABASES" },
   {
    "name": "jm_measurement",
    "query": "SHOW MEASUREMENTS ON \"$jm_database\""
   },
   {
    "name": "jm_retention",
    "query": "SHOW RETENTION POLICIES on \"$jm_database\""
   },
   {
    "name": "jm_application",
    "query": "SHOW TAG VALUES ON \"$jm_database\" FROM \"$jm_measurement\" WITH KEY = \"application\""
   },
   {
    "name": "jm_transaction",
    "query": "SHOW TAG VALUES ON \"$jm_database\" FROM \"$jm_measurement\" WITH KEY = \"transaction\""
   },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   },
   { "name": "server" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests - Client (j)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Requests - Client (j)",
   "type": "singlestat",
   "description": "failed requests for *all* transactions of a single measurement",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Received Bytes - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"rb\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sent Bytes - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "format": "bytes",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"sb\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Rate % - Client (j)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "format": "percentunit",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"error\") / sum(\"all\") FROM (SELECT sum(\"count\") AS \"all\" FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)), (SELECT sum(\"countError\") AS \"error\" FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Response Times 99,95,90% - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "99%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct99.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "95%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct95.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "90%",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"pct90.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND \"transaction\"='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "pct95.0" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Threads - Client (j)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"maxAT\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'internal' AND $timeFilter ) GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Throughput by operation - Client (j)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "modify",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~/^Mod.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "bind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^Bind.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "search",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (sum(\"count\") / $send_interval)/2 FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" =~ /^Search.*/ AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "alias": "all",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") / $send_interval FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" != '' AND \"transaction\" = 'all' AND $timeFilter ) GROUP BY  time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Response Times (99th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "all_transactions",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct99.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND transaction='all') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Response Times (95th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct95.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Response Times (90th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct90.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Response Times (99th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "total",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT max(\"pct99.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/ AND transaction !='all') AND $timeFilter GROUP BY  time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Response Times (95th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct95.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Response Times (90th pct) - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "transaction" ], "type": "tag" }
       ],
       "measurement": "jmeter",
       "query": "SELECT mean(\"pct90.0\") FROM \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE (\"application\" =~ /^$jm_application$/) AND $timeFilter GROUP BY \"transaction\", time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "statut", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Errors - Client (j)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Num of Errors",
       "groupBy": [
        { "params": [ "$aggregation" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "query": "SELECT sum(\"countError\") FROM  \"$jm_database\".\"$jm_retention\".\"$jm_measurement\" WHERE ( \"application\" =~ /^$jm_application$/ AND \"transaction\" =~ /^$jm_transaction$/ AND $timeFilter ) GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "countError" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "transaction", "operator": "=", "value": "all" },
        { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$application$/" }
       ]
      }
     ]
    },
    { "title": "Error Info - Client (j)", "type": "table-old", "gridPos": { "h": 7, "w": 16, "x": 8, "y": 38 } },
    {
     "title": "Errors per Transaction - Client (j)",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 }
    }
   ]
  }
 ]
}