apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pingdirectory-gp2
  labels:
    app: pingdirectory
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
mountOptions:
  - discard