kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  role: pingdatagovernance

resources:
- pingdatagovernance.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdatagovernance-environment-variables
  env: env_vars