apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdatagovernance
  name: pingdatagovernance
spec:
  ports:
  - name: http
    port: 80
  - name: https
    port: 1443
  - name: ldaps
    port: 1636
  selector:
    role: pingdatagovernance
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingdatagovernance
  name: pingdatagovernance
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingdatagovernance
  template:
    metadata:
      labels:
        role: pingdatagovernance
      name: pingdatagovernance
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: pingdatagovernance-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingdatagovernance:edge
        name: pingdatagovernance
        ports:
        - containerPort: 80
        - containerPort: 1443
        - containerPort: 1636
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi