apiVersion: v1
kind: Service
metadata:
  name: pingdatagovernance
spec:
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdatagovernance
spec:
  replicas: 1
  template:
    metadata:
      name: pingdatagovernance
      labels:
        app: pingdatagovernance
    spec:
      containers:
      - name: pingdatagovernance
        image: pingidentity/pingdatagovernance:edge
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: pingdatagovernance-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
