kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  role: pingdirectory

resources:
- pingdirectory.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  envs:
    - env_vars
