apiVersion: v1
kind: Service
metadata:
  name: pingdirectory
spec:
  ports:
    - port: 636
      name: ldaps
    - port:  443
      name: ssl
    - port:  389
      name: ldap
  clusterIP: None
  selector:
    app: pingdirectory
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectory
spec:
  serviceName: pingdirectory
  replicas: 1
  template:
    metadata:
      name: pingdirectory
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: pingdirectory
        image: pingidentity/pingdirectory:edge
        imagePullPolicy: Always
        ports:
        - containerPort: 636
        - containerPort:  443
        - containerPort:  389
        resources:
          requests:
            memory: "2Gi"
            cpu: "2"
          limits:
            memory: "2Gi"
            cpu: "2"
        envFrom:
        - configMapRef:
            name: pingdirectory-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        readinessProbe:
          exec:
            command: 
              - /bin/sh
              - -c
              - /opt/liveness.sh
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - /opt/liveness.sh
          initialDelaySeconds: 300
          periodSeconds: 30
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - /preStop.sh