version: "2.4"
# This server profile used as basis for ping-devop docker-launch

#-------------------------------------------------------------------------------------
#- Ping Identity PingAccess getting started demo
#-
#-                +---------------+
#-                |   PingAccess  |
#-                +---------------+
#-
#- To access PingAccess Console
#- 
#-    https://localhost:9000/
#-    
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

services:
  pingaccess:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingaccess:${PING_IDENTITY_DEVOPS_TAG}
    environment:
      - SERVER_PROFILE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=getting-started/pingaccess
    env_file:
      - ~/.pingidentity/devops
    ports:
      - "3000:3000"
      - "9000:9000"
    networks:
      - pingnet
                    
networks:
    pingnet:

