apiVersion: v1
kind: Service
metadata:
  name: pingaccess
spec:
  ports:
    - port: 9000
      name: pa-admin
    - port: 443
      name: pa-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingaccess
spec:
  replicas: 1
  template:
    metadata:
      name: pingaccess
    spec:
      containers:
      - name: pingaccess
        image: pingidentity/pingaccess:6.0.0-alpine-edge
        ports:
        - containerPort: 9000
        - containerPort: 443
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1"
          limits:
            memory: "1.5Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: pingaccess-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
