apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-config
  namespace: ping
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: config-reader
  apiGroup: rbac.authorization.k8s.io