apiVersion: v1
kind: Service
metadata:
  name: pingdataconsole
  labels:
    app: pingdataconsole
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: pingdataconsole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdataconsole
  labels:
    app: pingdataconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingdataconsole
  template:
    metadata:
      name: pingdataconsole
      labels:
        app: pingdataconsole
    spec:
      containers:
      - name: pingdataconsole
        image: pingidentity/pingdataconsole:edge
        ports:
        - containerPort: 8080
