apiVersion: v1
kind: Service
metadata:
  name: pingfederate
spec:
  ports:
    - port: 9999
      name: pf-console
    - port: 9031
      name: pf-runtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
spec:
  replicas: 1
  template:
    metadata:
      name: pingfederate
    spec:
      containers:
      - name: pingfederate
        image: pingidentity/pingfederate:edge
        ports:
        - containerPort: 9999
        - containerPort: 9031
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1"
          limits:
            memory: "1.5Gi"
            cpu: "1"
        env:
        - name: SERVER_PROFILE_URL
          value: "https://www.github.com/pingidentity/pingidentity-server-profiles.git"
        - name: SERVER_PROFILE_PATH
          value: "getting-started/pingfederate"
        envFrom:
        - secretRef:
            name: devops-secret
            optional: true
