apiVersion: v1
kind: Service
metadata:
  name: pingfederate
spec:
  ports:
    - port: 9999
      name: pf-console
    - port: 9031
      name: pf-runtime
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingfederate
spec:
  replicas: 1
  template:
    metadata:
      name: pingfederate
    spec:
      containers:
      - name: pingfederate
        image: pingidentity/pingfederate:edge
        ports:
        - containerPort: 9999
        - containerPort: 9031
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "1"
          limits:
            memory: "1.5Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: pingfederate-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        readinessProbe:
          httpGet:
            path: /pf/heartbeat.ping
            port: 9031
            scheme: HTTPS
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /pf/heartbeat.ping
            port: 9031
            scheme: HTTPS
          periodSeconds: 1
          initialDelaySeconds: 100
          failureThreshold: 1
