apiVersion: v1
kind: Service
metadata:
  name: pingdataconsole
  labels:
    usecase: fullstack
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: pingdataconsole
  selector:
    usecase: fullstack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingdataconsole
  labels:
    usecase: fullstack
spec:
  replicas: 1
  selector:
    matchLabels:
      usecase: fullstack
  template:
    metadata:
      name: pingdataconsole
      labels:
        usecase: fullstack
    spec:
      containers:
      - name: pingdataconsole
        image: pingidentity/pingdataconsole:edge
        ports:
        - containerPort: 8080
          name: pingdataconsole
