kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- pingfederate-admin.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingfederate-admin-environment-variables
  envs:
    - env_vars.pingfederate-admin
