mappings:
    # operation response time and throughput
  - match: "*.*.response-time"
    name: "response_time"
    labels:
      operation: "$2"
  - match: "*.*.throughput"
    name: "throughput"
    labels:
      operation: "$2"
    # connection handler metrics
  - match: "*.*.*.*.ldap-conn-handler-bytes-read"
    name: "LDAP_connection_handler_bytes_read"
    labels:
      port: "$4"
  - match: "*.*.*.*.ldap-conn-handler-bytes-written"
    name: "LDAP_connection_handler_bytes_written"
    labels:
      port: "$4"
  - match: "*.*.*.*.ldap-conn-handler-messages-read"
    name: "LDAP_connection_handler_messages_read"
    labels:
      port: "$4"
  - match: "*.*.*.*.ldap-conn-handler-messages-written"
    name: "LDAP_connection_handler_messages_written"
    labels:
      port: "$4"
  - match: "*.*.*.*.ldap-conn-handler-search-requests"
    name: "LDAP_connection_handler_search_requests"
    labels:
      port: "$4"
  - match: "*.*.*.*.ldap-conn-handler-search-entries-returned"
    name: "LDAP_connection_handler_search_entries_returned"
    labels:
      port: "$4"
    # backend metrics
  - match: "*.backend-entry-count"
    name: "backend_entry_count"
    labels:
      backendID: "$1"
  - match: "*.backend-db-cache-percent-full"
    name: "backend_db_cache_percent_full"
    labels:
      backendID: "$1"
  - match: "*.backend-size-on-disk"
    name: "backend_size_on_disk"
    labels:
      backendID: "$1"
  - match: "*.backend-active-cleaner-threads"
    name: "backend_active_cleaner_threads"
    labels:
      backendID: "$1"
  - match: "*.backend-cleaner-backlog"
    name: "backend_cleaner_backlog"
    labels:
      backendID: "$1"
  - match: "*.backend-nodes-evicted"
    name: "backend_nodes_evicted"
    labels:
      backendID: "$1"
  - match: "*.backend-checkpoints"
    name: "backend_checkpoints"
    labels:
      backendID: "$1"
  - match: "*.backend-avg-checkpoint-duration"
    name: "backend_avg_checkpoint_duration"
    labels:
      backendID: "$1"
  - match: "*.backend-time-since-last-checkpoint"
    name: "backend_time_since_last_checkpoint"
    labels:
      backendID: "$1"
  - match: "*.backend-new-db-logs"
    name: "backend_new_db_logs"
    labels:
      backendID: "$1"
  - match: "*.backend-random-reads"
    name: "backend_random_reads"
    labels:
      backendID: "$1"
  - match: "*.backend-random-writes"
    name: "backend_random_writes"
    labels:
      backendID: "$1"
  - match: "*.backend-sequential-reads"
    name: "backend_sequential_reads"
    labels:
      backendID: "$1"
  - match: "*.backend-sequential-writes"
    name: "backend_sequential_writes"
    labels:
      backendID: "$1"
    # entry cache metrics
  - match: "*.entry-cache-hit-ratio"
    name: "entry_cache_hit_ratio"
    labels:
      entryCache: "$1"
  - match: "*.entry-cache-hit-count"
    name: "entry_cache_hit_count"
    labels:
      entryCache: "$1"
  - match: "*.entry-cache-attempts"
    name: "entry_cache_attempts"
    labels:
      entryCache: "$1"
  - match: "*.entry-cache-add-or-update"
    name: "entry_cache_add_or_update"
    labels:
      entryCache: "$1"
  - match: "*.entry-cache-size"
    name: "entry_cache_size"
    labels:
      entryCache: "$1"
  - match: "*.entry-cache-pct-full"
    name: "entry_cache_pct_full"
    labels:
      entryCache: "$1"
    # changelog metrics?
  - match: "changelog.*"
    name: "$1"
    lables:
      backendID: "changelog"
    # GC metrics
  - match: "*.*.*.garbage-collections"
    name: "garbage_collections"
    labels:
      gcType: "$1"
      size: "$2"
      cause: "$3"
  - match: "*.*.*.garbage-collection-duration"
    name: "garbage_collection_duration"
    labels:
      gcType: "$1"
      size: "$2"
      cause: "$3"
  - match: "*.garbage-collection-live-mbytes"
    name: "garbage_collection_live_megabytes"
    labels:
      region: "$1"
