## Deployed with:
##  helm upgrade --install telegraf influxdata/telegraf-operator -f /Users/samirgandhi/projects/cluster-metrics-stack/telegraf/values.yaml -n metrics --version 1.3.11

# For demonstration only; default is 3 replicas
replicaCount: 1
image:
  repository: quay.io/influxdb/telegraf-operator
  pullPolicy: IfNotPresent
  sidecarImage: "docker.io/library/telegraf:1.30.0-alpine"

classes:
  secretName: "telegraf-operator-classes"
  default: "infra"
  data:
    infra: |
      [[outputs.influxdb]]
        urls = ["http://influxdb.influxdb:8086"]
      [global_tags]
        env = "ci"
        hostname = "$HOSTNAME"
        nodename = "$NODENAME"
        type = "infra"
    prometheus: |
      [[outputs.prometheus_client]]
        listen = ":9273"
        metric_version = 1
        path = "/metrics"
        expiration_interval = "30d"  # 60s
        collectors_exclude = ["gocollector", "process"]

certManager:
  enable: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  annotations: {}
podSecurityContext: {}
securityContext: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi
sidecarResources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 10m
    memory: 10Mi
nodeSelector: {}
tolerations: []
affinity: {}
requireAnnotationsForSecret: false
enableDefaultInternalPlugin: true
# allow hot reload ; disabled by default to support versions of telegraf
# that do not support hot-reload and --watch-config flag
hotReload: false
