{
 "title": "Ping Identity Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   { "name": "range_interval", "label": "range_interval", "query": "1m" },
   {
    "name": "send_interval",
    "label": "Backend send interval in second",
    "query": "5"
   },
   { "name": "server", "query": ".*ping.*" },
   { "name": "data_source", "query": "Prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PF Instance Overview (p)",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pingfederate_heartbeat_total_transactions{namespace=\"$namespace\"}"
    },
    {
     "expr": "pingfederate_heartbeat_total_failed_transactions{namespace=\"$namespace\"}"
    },
    {
     "expr": "pingfederate_heartbeat_number_of_cpus{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "pingfederate_heartbeat_total_jvm_memory{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PD Total Transactions by Operation (p)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pingdirectory_monitor_bind_op_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Bind"
    },
    {
     "expr": "sum(pingdirectory_monitor_search_op_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Search"
    },
    {
     "expr": "sum(pingdirectory_monitor_add_op_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Add"
    },
    {
     "expr": "sum(pingdirectory_monitor_modify_op_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Modify"
    },
    {
     "expr": "sum(pingdirectory_monitor_compare_op_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Compare"
    },
    {
     "expr": "sum(pingdirectory_monitor_delete_op_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(pingdirectory_monitor_extended_op_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Extended"
    }
   ]
  },
  {
   "title": "PD Operation Propensity (p)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pingdirectory_monitor_bind_op_total_count{namespace=\"$namespace\"}) /sum(pingdirectory_monitor_all_ops_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Bind"
    },
    {
     "expr": "sum(pingdirectory_monitor_search_op_total_count{namespace=\"$namespace\"})/sum(pingdirectory_monitor_all_ops_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Search"
    },
    {
     "expr": "sum(pingdirectory_monitor_add_op_total_count{namespace=\"$namespace\"})/sum(pingdirectory_monitor_all_ops_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Add"
    },
    {
     "expr": "sum(pingdirectory_monitor_modify_op_total_count{namespace=\"$namespace\"})/sum(pingdirectory_monitor_all_ops_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Modify"
    },
    {
     "expr": "sum(pingdirectory_monitor_compare_op_total_count{namespace=\"$namespace\"})/sum(pingdirectory_monitor_all_ops_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Compare"
    },
    {
     "expr": "sum(pingdirectory_monitor_delete_op_total_count{namespace=\"$namespace\"})/sum(pingdirectory_monitor_all_ops_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(pingdirectory_monitor_extended_op_1_3_6_1_4_1_30221_1_6_1_total_count{namespace=\"$namespace\"})/sum(pingdirectory_monitor_all_ops_total_count{namespace=\"$namespace\"})",
     "legendFormat": "Extended"
    }
   ]
  },
  {
   "title": "PF Logins Per Second - Server (p)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pingfederate_heartbeat_total_transactions{namespace=\"$namespace\"}[30s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PF Response Time 90th% - Server (p)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pingfederate_heartbeat_response_time_statistics_90_percentile{namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PF CPU Load by Server - Server (p)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pingfederate_heartbeat_cpu_load{namespace=\"$namespace\"})by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PD Throughput by Operation - Server (p)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (throughput{namespace=\"$namespace\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "PD Avg Response Time by Operation - Server (p)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (response_time{namespace=\"$namespace\"})",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "CPU usage % of Limit - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{image!=\"\", container=~\"$server\",namespace=\"$namespace\"}[5m])\n    ) by (pod,container)\n      /\n    sum(\n      container_spec_cpu_quota{image!=\"\", container=~\"$server\",namespace=\"$namespace\"} / container_spec_cpu_period{image!=\"\", container=~\"$server\",namespace=\"$namespace\"}\n    ) by (pod,container)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Used (%) - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{container=~\"$server\", namespace=\"$namespace\", image!=\"\"}) by (container, pod, namespace)\n      /\n    sum(container_spec_memory_limit_bytes{namespace=\"$namespace\"} > 0) by (container, pod, namespace)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network io bytes out - Server/client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod!=\"\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Network io bytes in - Server (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=~\"$server.*\"}[1m])) by (pod)"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "PF Session State Attribute Map Size- Server (p)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(pingfederate_heartbeat_session_state_attribute_map_size{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PF SP Session Registry Map Size - Server (p)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(pingfederate_heartbeat_sp_session_registry_session_map_size{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PF SP Session Registry Map Size - Server (p)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(pingfederate_heartbeat_sp_session_registry_session_map_size{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PF Total System Memory - Server (p)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "sum(pingfederate_heartbeat_total_physical_system_memory{namespace=\"$namespace\"}/1073741824)"
    }
   ]
  },
  {
   "title": "CPU - # of cores - Server (k)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{container_name=~\"$server\",namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "kube_pod_container_resource_requests"
    }
   ]
  },
  {
   "title": "PF Used JVM Memory % - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(pingfederate_heartbeat_used_jvm_memory{namespace=\"$namespace\"})/(pingfederate_heartbeat_total_jvm_memory{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used (GiB) - Server (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{container_name=~\"$server\",namespace=\"$namespace\"}) by (pod_name))/1073741824",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "CPU - # of cores - Client (k)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod!~\"ping.*\",namespace=\"$namespace\"}[$range_interval])) by (pod_name) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "PF Free JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "pingfederate_heartbeat_free_jvm_memory{namespace=\"$namespace\"}/1073741824",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Used (GiB) - Client (k)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{pod_name!~\"ping.*\",namespace=\"$namespace\"}) by (pod_name))/1073741824",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "PF Response Concurrency 90th% - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pingfederate_heartbeat_response_concurrency_statistics_90_percentile{namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PF Statisticss Window - Server (p)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(pingfederate_heartbeat_response_statistics_window_seconds{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PF Responses in Window Count - Server (p)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pingfederate_heartbeat_response_statistics_count{namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PF Response Time Min - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pingfederate_heartbeat_response_time_statistics_min{namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PF Response Time Max - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pingfederate_heartbeat_response_time_statistics_max{namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PF Response Concurrency Max - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pingfederate_heartbeat_response_concurrency_statistics_max{namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PF Response Concurrency Min - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pingfederate_heartbeat_response_concurrency_statistics_min{namespace=\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PF Errors Per Second - Server (p)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pingfederate_heartbeat_total_failed_transactions{namespace=\"$namespace\"}[30s])"
    }
   ]
  }
 ]
}