apiVersion: v1
data:
  K8S_STATEFUL_SET_NAME: pingdirectory-east
  K8S_STATEFUL_SET_SERVICE_NAME: pingdirectory-cluster-east
  K8S_CLUSTERS: west east
  K8S_CLUSTER: east
  K8S_SEED_CLUSTER: west
  K8S_NUM_REPLICAS: "3"
  K8S_POD_HOSTNAME_PREFIX: pingdirectory-
  K8S_POD_HOSTNAME_SUFFIX:  -east
  K8S_SEED_HOSTNAME_SUFFIX:  -west
  K8S_INCREMENT_PORTS: "false"
  REPLICATION_PORT: "8989"
  LDAP_PORT: "1389"
  LDAPS_PORT: "1636"
  HTTPS_PORT: "1443"
  PING_CONTAINER_PRIVILEGED: "false"
  MAKELDIF_USERS: "1000"
  ORCHESTRATION_TYPE: KUBERNETES
  PING_IDENTITY_ACCEPT_EULA: "YES"
  SERVER_PROFILE_PATH: baseline/pingdirectory
  SERVER_PROFILE_URL: https://www.github.com/pingidentity/pingidentity-server-profiles.git
  TAIL_LOG_FILES: '""'

kind: ConfigMap
metadata:
  annotations: {}
  labels:
    role: pingdirectory
    cluster: east
  name: pingdirectory-east-environment-variables

---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdirectory
    cluster: east
  name: pingdirectory-east
spec:
  ports:
  - name: ldaps
    port: 1636
  - name: ssl
    port: 1443
  - name: ldap
    port: 1389
  selector:
    role: pingdirectory
    cluster: east

---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdirectory
    cluster: east
  name: pingdirectory-0-east
spec:
  ports:
  - name: ldaps
    port: 1636
  - name: replication
    port: 8989
  selector:
    statefulset.kubernetes.io/pod-name: pingdirectory-east-0
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdirectory
    cluster: east
  name: pingdirectory-1-east
spec:
  ports:
  - name: ldaps
    port: 1636
  - name: replication
    port: 8989
  selector:
    statefulset.kubernetes.io/pod-name: pingdirectory-east-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdirectory
    cluster: east
  name: pingdirectory-2-east
spec:
  ports:
  - name: ldaps
    port: 1636
  - name: replication
    port: 8989
  selector:
    statefulset.kubernetes.io/pod-name: pingdirectory-east-2

---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingdirectory
    cluster: east
  name: pingdirectory-cluster-east
spec:
  clusterIP: None
  ports:
  - name: ldaps
    port: 1636
  selector:
    role: pingdirectory
    cluster: east
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    role: pingdirectory
    cluster: east
  name: pingdirectory-east
spec:
  replicas: 2
  selector:
    matchLabels:
      role: pingdirectory
      cluster: east
  serviceName: pingdirectory-cluster-east
  template:
    metadata:
      labels:
        role: pingdirectory
        cluster: east
      name: pingdirectory
    spec:
      nodeSelector: {}
      containers:
      - envFrom:
        - configMapRef:
            name: pingdirectory-east-environment-variables
        - secretRef:
            name: devops-secret
            optional: true
        image: pingidentity/pingdirectory:edge
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /preStop.sh
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/liveness.sh
          initialDelaySeconds: 300
          periodSeconds: 30
        name: pingdirectory
        ports:
        - containerPort: 1636
        - containerPort: 1443
        - containerPort: 1389
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /opt/liveness.sh
        resources:
          limits:
            cpu: "6"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 2Gi
  #       volumeMounts:
  #       - mountPath: /opt/out
  #         name: out-dir
  #     terminationGracePeriodSeconds: 300
  #     volumes:
  #     - name: out-dir
  #       persistentVolumeClaim:
  #         claimName: out-dir
  # volumeClaimTemplates:
  # - metadata:
  #     name: out-dir
  #   spec:
  #     accessModes:
  #     - ReadWriteOnce
  #     resources:
  #       requests:
  #         storage: 3Gi
