name: Deploy Docs
on:
  push:
    branches:
      - master
    paths:
      - 'mkdocs.yml'
      - 'docs/**/*'
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-redirects
      - run: mkdocs gh-deploy --force
